services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "itfs"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6543:5432"

  frontend:
      container_name: nextapp
      image: francescoxx/nextapp:1.0.0
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      ports:
        - 3000:3000
      depends_on:
        - backend
      restart: always

  backend:
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    build:
      context: ./
      dockerfile: backend/Dockerfile
      target: app
    environment:
      SPRING_PROFILES_ACTIVE: docker

  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:8080