import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ToastProvider from '@/utils/providers/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'itfs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru' className={'leading-tight text-gray-900 antialiased'}>
      <body className={`${inter.className} min-h-screen bg-gray-100`}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
